export interface IAlphabet {
  morse: string;
  spelling: string;
}

export class Alphabet {
  static readonly alphabet: { [key: string]: IAlphabet } = {
    'A': {morse: '.-', spelling: 'Alfa'},
    'B': {morse: '-...', spelling: 'Bravo'},
    'C': {morse: '-.-.', spelling: 'Charlie'},
    'D': {morse: '-..', spelling: 'Delta'},
    'E': {morse: '.', spelling: 'Echo'},
    'F': {morse: '..-.', spelling: 'Foxtrot'},
    'G': {morse: '--.', spelling: 'Golf'},
    'H': {morse: '....', spelling: 'Hotel'},
    'I': {morse: '..', spelling: 'India'},
    'J': {morse: '.---', spelling: 'Juliett'},
    'K': {morse: '-.-', spelling: 'Kilo'},
    'L': {morse: '.-..', spelling: 'Lima'},
    'M': {morse: '--', spelling: 'Mike'},
    'N': {morse: '-.', spelling: 'November'},
    'O': {morse: '---', spelling: 'Oscar'},
    'P': {morse: '.--.', spelling: 'Papa'},
    'Q': {morse: '--.-', spelling: 'Quebec'},
    'R': {morse: '.-.', spelling: 'Romeo'},
    'S': {morse: '...', spelling: 'Sierra'},
    'T': {morse: '-', spelling: 'Tango'},
    'U': {morse: '..-', spelling: 'Uniform'},
    'V': {morse: '...-', spelling: 'Victor'},
    'W': {morse: '.--', spelling: 'Whisky'},
    'X': {morse: '-..-', spelling: 'Xray'},
    'Y': {morse: '-.--', spelling: 'Yankee'},
    'Z': {morse: '--..', spelling: 'Zulu'},
    '0': {morse: '-----', spelling: 'Zero'},
    '1': {morse: '.----', spelling: 'One'},
    '2': {morse: '..---', spelling: 'Two'},
    '3': {morse: '...--', spelling: 'Three'},
    '4': {morse: '....-', spelling: 'Four'},
    '5': {morse: '.....', spelling: 'Five'},
    '6': {morse: '-....', spelling: 'Six'},
    '7': {morse: '--...', spelling: 'Seven'},
    '8': {morse: '---..', spelling: 'Eight'},
    '9': {morse: '----.', spelling: 'Nine'},
    '.': {morse: '.-.-.-', spelling: 'Period'},
    ',': {morse: '--..--', spelling: 'Comma'},
    '?': {morse: '..--..', spelling: 'Question mark'},
    '!': {morse: '-.-.--', spelling: 'Exclamation mark'},
    '-': {morse: '-....-', spelling: 'Dash'},
    '*': {morse: '-..-', spelling: 'star'},
    '/': {morse: '-..-.', spelling: 'slash'},
    ':': {morse: '---...', spelling: 'colon'},
    '\'': {morse: '.----.', spelling: 'quote'},
    '"': {morse: '.-..-.', spelling: 'double quote'},
    ')': {morse: '-.--.-', spelling: 'parenthesis close'},
    ';': {morse: '-.-.-', spelling: 'semi colon'},
    '(': {morse: '-.--.', spelling: 'parenthesis open'},
    '=': {morse: '-...-', spelling: 'equals'},
    '@': {morse: '.--.-.', spelling: 'at'},
    '&': {morse: '.-...', spelling: 'ampersand'},
    '+': {morse: '.-.-.', spelling: 'plus'},
    ' ': {morse: ' ', spelling: 'space'},
  };
}

