:hardbreaks-option:
= Farnsworth timing of morsecode
Vicky Ronnen <pa5wpm@pa5wpm.nl>
1.0 December 28, 2025
:toc:
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

== Terminology

===  WPM

WPM is an acronym for Words Per Minute.
How many times per minute the word PARIS *including one space at the end* is sent.

=== Ticks

A morse letter is composed of dots (.), dash (-) and silences.

|===
|Type |Ticks

|dot .
|1

|dash -
|3

|silence between . or -
|1

|silence between letters
|3

|silence between words
|7
|===

=== Farnsworth

Learning morse code by lengthening the tick duration affects the way Morse code is perceived.
Increasing the speed is more challenging because you trained detecting dots and dashes and then combining them.
A triplet in music is played as a unit and not counted out.
Learning rhythm patterns is the key in music.
In the idea of Farnsworth is to learn letters as a pattern, not the individual dots and dashes.
So speed up the word speed in letters so you cannot determine the individual dot and dashes, but increase the silence between letters and words.
For speeds at 18 WPM and above, the silence is the same as in the chosen speed.

=== Tick time

The tick time is computed as follows:

|===
|Letter|Morse|Ticks in letter|Ticks in letter|Ticks after letter
|P|. - - .|1+1 + 3+1 + 3+1 + 1|11|3
|A|. -|1+1 + 3|5|3
|R|. - .|1+1 + 3+1 + 1|7|3
|I|. .|1+1 + 1|3|3
|S|. . .|1+1 + 1+1 + 1|5|0
|space||0|0|7
|===

So the word 'PARIS ' contains 11+3 + 5+3 + 7+3 + 3+3 + 5+0 +7 = 14 + 8 + 10 + 6 + 5 + 7 = 50 ticks.

Let stem:[T_l] the tick time in letters at 18 WPM.
Let stem:[T_s] in silence at 5 WPM.

At 18 WPM a stem:[T_l] lasts for stem:[60 / (18 * 50)] = 0.0666667 seconds or 66.67 ms.
In the word *'PARIS '* we have 11 + 5 + 7 + 3 + 5 = 31 ticks in the letters and 50 - 31 = 19 silence ticks between letters.
By making the silence ticks longer, the effective WPM is lowered.

Let *stem:[W_c]* the character speed
Let *stem:[W_e]* the effective word speed

stem:[T_l=60/(50W_c)=60 / (50*18) = 0.06667s\ (66.67ms)]

stem:[60=W_e*(31T_l+19T_s)] => stem:[60/W_e=31T_l+19T_s] => stem:[60/W_e-31T_l=19T_s]=>stem:[T_s=60/(19W_e)-31/19T_l]

substituting stem:[T_l] gives for stem:[W_e=5] and stem:[W_c=18]

stem:[T_s=60/(19W_e)-31/19(60/(50W_c))] => stem:[T_s=60/(19*5)-31/19(60/(50*18))]=stem:[0.5228s\ (522.8ms) ]
